### ISSUE TITLE
InvalidOperationException after updating from 4.5.0 to 4.6.0

### ISSUE THREAD

**Issue by ff-ils** [dotnet/roslynator#1230] opened 2023-10-23 08:03 UTC
In a project where version 4.5.0 worked without problems, after updating to 4.6.0 during build this error appears multiple times:

`CSC : warning AD0001: Analyzer 'Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Object is not initialized.'.`

Installing Visual Studio extension the error is

Severity	Code	Description	Project	Path	File	Line	Suppression State
Warning	AD0001	Analyzer 'Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Object is not initialized.'.
Exception occurred with following context:
Compilation: PROJECTNAME
SyntaxTree: CS_FILE
SyntaxNode: variable.AppendLine() [InvocationExpressionSyntax]@[465..487) (19,2)-(19,24)

System.InvalidOperationException: Object is not initialized.
   at Roslynator.CSharp.Syntax.SimpleMemberInvocationExpressionInfo.get_Name()
   at Roslynator.CSharp.Syntax.SimpleMemberInvocationExpressionInfo.get_NameText()
   at Roslynator.CSharp.Analysis.OptimizeStringBuilderAppendCallAnalysis.Analyze(SyntaxNodeAnalysisContext context, SimpleMemberInvocationExpressionInfo& invocationInfo)
   at Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer.AnalyzeInvocationExpression(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__49`1.<ExecuteSyntaxNodeAction>b__49_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)

The reported line is

`stringBuilder.AppendLine();`

**Comment by josefpihrt** [comment] 2023-10-23 09:09
Duplicate of https://github.com/dotnet/roslynator/issues/1225

**Comment by josefpihrt** [comment] 2023-10-23 09:10
Patch will be released soon.

**Closed by josefpihrt** 2023-10-23 09:10 UTC

**Comment by josefpihrt** [comment] 2023-10-23 19:03
https://github.com/dotnet/roslynator/releases/tag/v4.6.1
