### ISSUE TITLE
AddExceptionToDocumentationCommentAnalyzer NRE

### ISSUE THREAD

**Issue by bdovaz** [dotnet/roslynator#1556] opened 2024-10-10 10:20 UTC
`CSC : error AD0001: Analyzer 'Roslynator.CSharp.Analysis.AddExceptionToDocumentationCommentAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null. (Parameter 'syntax')'`

https://github.com/dotnet/roslynator/blob/ca8d20f47943e0ad6d3eb449b9e06f9e15b3ca51/src/Analyzers/CSharp/Analysis/AddExceptionToDocumentationCommentAnalyzer.cs#L14

I can't tell you exactly where the problem comes from because it doesn't tell me which script it is in....

In my case I run it from Unity in case it helps at all.

**Comment by josefpihrt** [comment] 2024-10-10 10:21
duplicate of #1553

**Closed by josefpihrt** 2024-10-10 10:21 UTC
