### ISSUE TITLE
Fixing RCS1251 produces RCS0023 in csproj

### ISSUE THREAD

**Issue by daze99** [dotnet/roslynator#1348] opened 2024-01-08 13:18 UTC
**Product and Version Used**: 
Roslynator 4.8.0

**Steps to Reproduce**:
When applying the fix to
```csharp
namespace Test;

public static class Test
{
}
```
it produces the result
```csharp
namespace Test;

public static class Test;
```
This results then in a RCS0023 on the csproj file.

**Comment by josefpihrt** [comment] 2024-01-08 19:25
duplicate of #920

**Closed by josefpihrt** 2024-01-08 19:25 UTC
Labels: Bug, Area-Analyzers
