### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by BenjaminBrienen** [dotnet/roslynator#1423] opened 2024-03-14 21:08 UTC
Documentation does not exist for roslynator_blank_line_between_closing_brace_and_switch_section. In fact, there are 0 search results on Google and DuckDuckGo, but I can see that the config is being used in the codebase.

Also missing for RCS1082 UseCountOrLengthPropertyInsteadOfCountMethod
https://josefpihrt.github.io/docs/roslynator/analyzers/RCS1082

And RCS1115	ReplaceReturnStatementWithExpressionStatement
https://josefpihrt.github.io/docs/roslynator/analyzers/RCS1115

**Comment by josefpihrt** [comment] 2024-03-15 09:31
Ad `roslynator_blank_line_between_closing_brace_and_switch_section`: This option is obsolete as the "parent" analyzer is obsolete. It can be found here: https://josefpihrt.github.io/docs/roslynator/analyzers/RCS0014/

Ad RCS1082, RCS1115: these analyzers were completely removed from Roslynator (usually replaced with or merged into some other analyzer). I would say that there should not be any links to these analyzers. Where does these links come from?

**Comment by BenjaminBrienen** [comment] 2024-03-15 10:44
> Ad `roslynator_blank_line_between_closing_brace_and_switch_section`: This option is obsolete as the "parent" analyzer is obsolete. It can be found here: https://josefpihrt.github.io/docs/roslynator/analyzers/RCS0014/
> 
> Ad RCS1082, RCS1115: these analyzers were completely removed from Roslynator (usually replaced with or merged into some other analyzer). I would say that there should not be any links to these analyzers. Where does these links come from?

I wrote the links manually because I saw the definitions for those in the XML file. I was just trying to create an .editorconfig that enabled absolutely everything with at least a suggestion minimum severity. Every example of a "complete" config file seems to be missing one or two things. The XML file seemed to be the most up to date "source". Thus, I based mine on that, coming across a few discrepancies in the meanwhile.

**Comment by josefpihrt** [comment] 2024-03-15 11:09
The full list of options is available here: https://josefpihrt.github.io/docs/roslynator/configuration. You just need to choose value for options that can have multiple value and replace analyzer severity for analyzer that are not enabled by default.

Does that help?

**Comment by BenjaminBrienen** [comment] 2024-03-15 11:34
> The full list of options is available here: https://josefpihrt.github.io/docs/roslynator/configuration. You just need to choose value for options that can have multiple value and replace analyzer severity for analyzer that are not enabled by default.
> 
> Does that help?

I did find that, but there seemed to be a couple things missing from that list. Maybe it's only the unreleased and deprecated features you mentioned earlier. Thanks! Love the product, by the way. I needed Roslynator to point out unused expression values and many more tiny suggestions. The IDE analyzers aren't the best imo. It works amazingly well!

**Comment by josefpihrt** [comment] 2024-03-15 12:51
I'm really glad you like it!

**Comment by BenjaminBrienen** [comment] 2024-03-15 12:57
@josefpihrt this page https://josefpihrt.github.io/docs/roslynator/analyzers/RCS0014/ has a broken link https://josefpihrt.github.io/docs/roslynator/analyzers/RCS0014/RCS0061

**Comment by josefpihrt** [comment] 2024-03-15 14:24
I know about this issue. Weird is that when you refresh the page the link is correct (at least that is my experience). Maybe it has something to do with Docusaurus, but haven't found out yet. If you have any idea what could be the cause, it would be great.

**Closed** 2024-09-12 11:53 UTC
