### ISSUE TITLE
RCS1169: FP for Unity

### ISSUE THREAD

**Issue by bdovaz** [dotnet/roslynator#1200] opened 2023-09-11 08:16 UTC
**Product and Version Used**: 

4.5.0

**Steps to Reproduce**:

Unity has its own serialization system where if you mark for example a private field with the `[SerializeField]` attribute it allows you in the Unity IDE to edit the value of the field so it cannot be of type `readonly`.

https://docs.unity3d.com/ScriptReference/SerializeField.html

I know there are other analyzers that make the exception to ignore this rule if the field has an attribute because it may indicate that it is processed differently as in the case of Unity.

**Actual Behavior**:

Before:

```csharp
[SerializeField]
private int a;
```

After:

```csharp
[SerializeField]
private readonly int a;
```

**Expected Behavior**:
```csharp
[SerializeField]
private int a;
```

**Comment by josefpihrt** [comment] 2023-11-10 16:43
duplicate of #1236

**Closed by josefpihrt** 2023-11-10 16:43 UTC
Labels: Bug, Area-Analyzers, up-for-grabs
